Add s3am
BD2KGenomics/cgl-docker-lib pull request #188
Opened 2016-09-22 21:06 UTC by cket

Continued from #80

2016-09-22 21:11 UTC, hannes-ucsc commented on s3am/test.py
> +        self.assertTrue('usage: s3am [--help] {upload,cancel,verify} ...')
This is always True. You want `in out`

2016-09-22 21:12 UTC, hannes-ucsc commented on s3am/wrapper.sh
> +source /opt/s3am/bin/activate
Just invoke s3am by direct path. The venv will be activated on-the-fly.

2016-09-22 21:12 UTC, hannes-ucsc commented on s3am/Dockerfile
> +RUN virtualenv /opt/s3am && . /opt/s3am/bin/activate
Remove the sourcing of activate

2016-09-22 21:13 UTC, hannes-ucsc commented on s3am/Dockerfile
> +RUN pip install s3am==2.0
Invoke pip as /opt/s3am/bin/pip and the venv will be activated on the fly.

2016-09-22 21:16 UTC, hannes-ucsc commented on s3am/test.py
> +def check_docker_output(tool):
What does this give us over subprocess.check_output?

2016-09-22 21:16 UTC, hannes-ucsc commented on s3am/test.py
> +        self.assertTrue('usage: s3am [--help] {upload,cancel,verify} ...')
or `in err`

2016-09-22 21:17 UTC, hannes-ucsc commented on s3am/test.py
> +def check_docker_output(tool):
Other than not throwing CalledProcessException

2016-09-22 21:18 UTC, hannes-ucsc requested changes
@cket

2016-09-22 22:21 UTC, cket commented
@hannes-ucsc

2016-09-23 03:46 UTC, hannes-ucsc commented on s3am/Dockerfile
> +RUN virtualenv /opt/s3am
Pass --no-download to virtualenv

2016-09-23 03:47 UTC, hannes-ucsc commented on s3am/Dockerfile
> +ENTRYPOINT ["bash", "+x", "/opt/wrapper.sh"]
Lets omit the wrapper and make s3am the entry point. The perm fix is taken care of by docker_call now.

2016-09-23 03:49 UTC, hannes-ucsc commented on s3am/test.py
> +            print vars(e)
?

2016-09-23 03:51 UTC, hannes-ucsc commented on s3am/test.py
> +# @author Frank Austin Nothaft fnothaft@berkeley.edu
Remove this line

2016-09-23 03:51 UTC, hannes-ucsc commented on s3am/Dockerfile
> +MAINTAINER CJ Ketchum
Remove these two lines

2016-09-23 03:53 UTC, hannes-ucsc commented on s3am/Makefile
> +# Steps
Remove

2016-09-23 03:53 UTC, hannes-ucsc commented on s3am/Makefile
> +# Definitions
Remove

2016-09-23 03:54 UTC, hannes-ucsc requested changes
Main requested change is removal of wrapper

2016-09-23 19:50 UTC, cket commented
@hannes-ucsc ready

2016-09-23 20:10 UTC, hannes-ucsc approved these changes

2016-09-23 20:10 UTC, merged