Updated vg image to v1.4.0-1649-g8a28f7d
BD2KGenomics/cgl-docker-lib pull request #208
Opened 2016-12-01 23:56 UTC by cmarkello

2016-12-02 00:26 UTC, cmarkello commented
@hannes-ucsc Ready for review.

2016-12-02 03:33 UTC, fnothaft reviewed
Did you intend to drop the checkout of a specific commit?

2016-12-02 03:33 UTC, fnothaft commented on vg/build/Dockerfile
> -RUN git checkout 9aa20df8f71ebf67b0050e3c77db5f6e4cab256d
You should still be checking out a tag or commit from git, no?

2016-12-02 20:34 UTC, hannes-ucsc requested changes
Same concern as @fnothaft

2016-12-02 20:34 UTC, hannes-ucsc commented on vg/build/Dockerfile
> -RUN git checkout 9aa20df8f71ebf67b0050e3c77db5f6e4cab256d
Yes, you need to pin the commit you are checking out. Especially, if you are tagging the image as a specific version, i.e. v1.4.0-1649-g8a28f7d.

2016-12-05 19:10 UTC, hannes-ucsc commented
Build hung for two days.

Jenkins, test this please.

2016-12-05 20:08 UTC, cmarkello commented
@hannes-ucsc Ready for review.

2016-12-05 22:05 UTC, cmarkello commented
@hannes-ucsc @fnothaft Ready for review.

2016-12-05 23:17 UTC, hannes-ucsc approved these changes

2016-12-05 23:17 UTC, merged