Issues/229 upgrade gatk version
BD2KGenomics/cgl-docker-lib pull request #231
Opened 2017-03-02 21:14 UTC by tpesout

updated to latest: 3.7

2017-03-02 21:25 UTC, jvivian requested changes

2017-03-02 21:25 UTC, jvivian commented on gatk/build/Dockerfile
> +WORKDIR /home/
This change needed?

2017-03-02 21:25 UTC, jvivian commented on gatk/build/Dockerfile
> +RUN ls /home/gatk-protected/gatk-protected-3.7/
Why are you running `ls` here?

2017-03-02 21:25 UTC, jvivian commented on gatk/build/Dockerfile
> +RUN ls /home/gatk-protected/gatk-protected-3.7/target/
same

2017-03-02 21:25 UTC, jvivian commented on gatk/build/Dockerfile
> +WORKDIR /home/gatk-protected
By convention the final `WORKDIR` is set to **/data**

2017-03-02 21:25 UTC, jvivian commented on gatk/build/Dockerfile
>  	git \
Can remove `git` since you're not using it anymore

2017-03-02 21:29 UTC, fnothaft requested changes

2017-03-02 21:29 UTC, fnothaft commented on gatk/build/Dockerfile
>  RUN find . -name "*.java" -exec sed -i -e "s/import oracle.jrockit.jfr/\/\/import oracle.jrockit.jfr/g" {} \;
Is this line still needed in 3.7?

2017-03-02 23:29 UTC, tpesout commented on gatk/build/Dockerfile
>  RUN find . -name "*.java" -exec sed -i -e "s/import oracle.jrockit.jfr/\/\/import oracle.jrockit.jfr/g" {} \;
unfortunately yes :/

2017-03-02 23:30 UTC, jvivian commented on gatk/build/Dockerfile
>  RUN find . -name "*.java" -exec sed -i -e "s/import oracle.jrockit.jfr/\/\/import oracle.jrockit.jfr/g" {} \;
lololol

2017-03-02 23:30 UTC, fnothaft commented on gatk/build/Dockerfile
>  RUN find . -name "*.java" -exec sed -i -e "s/import oracle.jrockit.jfr/\/\/import oracle.jrockit.jfr/g" {} \;
thats hot

2017-03-03 18:41 UTC, jvivian approved these changes

2017-03-03 18:44 UTC, jvivian requested changes
Makefile tag needs updating to reflect version change.

2017-03-03 19:53 UTC, fnothaft approved these changes

2017-03-03 20:26 UTC, jvivian approved these changes

2017-03-04 01:22 UTC, jvivian commented
jenkins, test this please

2017-03-06 19:07 UTC, merged